In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# XMem　ダウンロード

In [1]:
import locale
locale.getpreferredencoding = lambda: "UTF-8"

In [2]:
!nvidia-smi

import torch

if torch.cuda.is_available():
  print('Using GPU')
  device = 'cuda'
else:
  print('CUDA not available. Please connect to a GPU instance if possible.')
  device = 'cpu'

Wed Nov 15 08:47:06 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
!git clone https://github.com/hkchengrex/XMem.git
%cd XMem
!pip install opencv-python
!pip install -U numpy
!pip install -r requirements.txt

Cloning into 'XMem'...
remote: Enumerating objects: 596, done.
remote: Counting objects: 100% (323/323), done.
remote: Compressing objects: 100% (127/127), done.
remote: Total 596 (delta 233), reused 210 (delta 195), pack-reused 273
Receiving objects: 100% (596/596), 265.06 KiB | 17.67 MiB/s, done.
Resolving deltas: 100% (345/345), done.
/content/XMem
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 71.0 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
cupy-cuda11x 1

In [4]:
# Download the pretrained model
!wget -P ./saves/ https://github.com/hkchengrex/XMem/releases/download/v1.0/XMem.pth

--2023-11-15 08:47:42--  https://github.com/hkchengrex/XMem/releases/download/v1.0/XMem.pth
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/511262077/ea2968ee-04ab-4dee-8596-03319e8c7e9f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231115T084742Z&X-Amz-Expires=300&X-Amz-Signature=8ee357681ef7944cefe3ff77aacc79ec9953152dab86c0f92e25c2e2a14d739d&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=511262077&response-content-disposition=attachment%3B%20filename%3DXMem.pth&response-content-type=application%2Foctet-stream [following]
--2023-11-15 08:47:42--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/511262077/ea2968ee-04ab-4dee-8596-03319e8c7e9f?X-Amz-Algorithm=AWS4-

In [5]:
# Basic setup
import os
from os import path
from argparse import ArgumentParser
import shutil

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader
import numpy as np
from PIL import Image

from inference.data.test_datasets import LongTestDataset, DAVISTestDataset, YouTubeVOSTestDataset
from inference.data.mask_mapper import MaskMapper
from model.network import XMem
from inference.inference_core import InferenceCore

from progressbar import progressbar

torch.set_grad_enabled(False)

# default configuration
config = {
    'top_k': 30,
    'mem_every': 5,
    'deep_update_every': -1,
    'enable_long_term': True,
    'enable_long_term_count_usage': True,
    'num_prototypes': 128,
    'min_mid_term_frames': 5,
    'max_mid_term_frames': 10,
    'max_long_term_elements': 10000,
}

network = XMem(config, './saves/XMem.pth').eval().to(device)

Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False


Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /root/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth
100%|██████████| 97.8M/97.8M [00:04<00:00, 23.9MB/s]
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /root/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 71.2MB/s]


## XMemを使って白選手をフォーカス

### 白選手のmaskを作る

In [6]:
os.chdir("/content/drive/MyDrive/Colab Notebooks/2023年度スポコン/データ/2018WC_3seconds")
mv_2018_ls = [os.getcwd() + "/" + file_name for file_name in os.listdir(os.getcwd()) if file_name[-6:-4] == "_1"]

FileNotFoundError: ignored

In [ ]:
mv_2018_ls[0]

'/content/drive/.shortcut-targets-by-id/1wERFTJ3tk-moekRG-4KtAeT8uJewI1Y3/データ/2018WC_3seconds/2018WCB_100_3M_DARWISH Ramadan_EGY_ILYASOV Niyaz_RUS_1.mp4'

In [ ]:
video_name = mv_2018_ls[0]
mask_name = "/content/drive/MyDrive/Colab Notebooks/sports/sports_competition/XMemで両選手フォーカス/サンプル/image_mask_1.png"

In [ ]:
# Convert the mask to a numpy array
mask = np.array(Image.open(mask_name))
mask1 = mask / 255
print(mask)
print(np.unique(mask1))
num_objects = len(np.unique(mask1)) - 1
print(num_objects)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0. 1.]
1


In [ ]:
mask1.shape

(360, 640)

In [ ]:
print(np.unique(mask_name))
num_objects = len(np.unique(mask_name)) - 1

[  0 255]


In [ ]:
mask = np.array(mask_name)
print(type(mask))

<class 'numpy.ndarray'>


In [ ]:
mask = np.array(Image.open(mask_name))
print(np.unique(mask))
num_objects = len(np.unique(mask)) - 1

AttributeError: ignored

In [ ]:
# Propagte frame-by-frame
import cv2
from inference.interact.interactive_utils import image_to_torch, index_numpy_to_one_hot_torch, torch_prob_to_numpy_mask, overlay_davis

torch.cuda.empty_cache()

processor = InferenceCore(network, config=config)
processor.set_all_labels(range(1, num_objects+1)) # consecutive labels
cap = cv2.VideoCapture(video_name)

# You can change these two numbers
frames_to_propagate = 200
visualize_every = 20

current_frame_index = 0

with torch.cuda.amp.autocast(enabled=True):
  while (cap.isOpened()):
    # load frame-by-frame
    _, frame = cap.read()
    if frame is None or current_frame_index > frames_to_propagate:
      break

    # convert numpy array to pytorch tensor format
    frame_torch, _ = image_to_torch(frame, device=device)
    if current_frame_index == 0:
      # initialize with the mask
      mask_torch = index_numpy_to_one_hot_torch(mask, num_objects+1).to(device)
      # the background mask is not fed into the model
      prediction = processor.step(frame_torch, mask_torch[1:])
    else:
      # propagate only
      prediction = processor.step(frame_torch)

    # argmax, convert to numpy
    prediction = torch_prob_to_numpy_mask(prediction)

    if current_frame_index % visualize_every == 0:
      visualization = overlay_davis(frame, prediction)
      display(Image.fromarray(visualization))

    current_frame_index += 1

RuntimeError: ignored

In [ ]:
from numpy.ma.core import count
import cv2
from inference.interact.interactive_utils import image_to_torch, index_numpy_to_one_hot_torch, torch_prob_to_numpy_mask, overlay_davis

torch.cuda.empty_cache()

processor = InferenceCore(network, config=config)
processor.set_all_labels(range(1, num_objects+1)) # consecutive labels
cap = cv2.VideoCapture(video_name)
# フレームの総数
totalframecount = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) - first_frame
print(totalframecount)
#指定したフレームをセットする
cap.set(cv2.CAP_PROP_POS_FRAMES, first_frame)

# You can change these two numbers
frames_to_propagate = totalframecount
visualize_every = 200

current_frame_index = 0
count_value = 0
with torch.cuda.amp.autocast(enabled=True):
  while (cap.isOpened()):
    # load frame-by-frame
    _, frame = cap.read()
    if frame is None or current_frame_index > frames_to_propagate:
      break

    # convert numpy array to pytorch tensor format
    frame_torch, _ = image_to_torch(frame, device=device)
    if current_frame_index == 0:
      # initialize with the mask
      mask_torch = index_numpy_to_one_hot_torch(mask, num_objects+1).to(device)
      # the background mask is not fed into the model
      prediction = processor.step(frame_torch, mask_torch[1:])
    else:
      # propagate only
      prediction = processor.step(frame_torch)

    # argmax, convert to numpy
    prediction = torch_prob_to_numpy_mask(prediction)

    if current_frame_index % visualize_every == 1:
      visualization = overlay_davis(frame, prediction)
      # display(Image.fromarray(visualization))
      #cv2_imshow(visualization)
    #動画にフレーム数を表示する
    frame = cv2.putText(frame, f'{count_value}', org = (50, 50), fontFace = cv2.FONT_HERSHEY_PLAIN, fontScale = 1, color = (255, 255, 255), thickness = 1, lineType = cv2.LINE_AA)
    writer.write(frame)
    count_value += 1
    current_frame_index += 1
  cap.release()
  writer.release()

NameError: ignored

# lang-segment-anything

## import

In [ ]:
# # before RAM increase
# !free -h
# [_ for _ in range(10000000000)]

In [ ]:
import os
os.chdir("/content/drive/MyDrive/Colab Notebooks/2023年度スポコン")

In [ ]:
# import
import sys
import os
import distutils.core

# import some common libraries
import numpy as np
import json
import cv2
import random


# import some common detectron2 utilities
# from detectron2 import model_zoo
# from detectron2.engine import DefaultPredictor
# from detectron2.config import get_cfg
# from detectron2.utils.visualizer import Visualizer
# from detectron2.data import MetadataCatalog, DatasetCatalog

# # 画像から動画変換用
# import matplotlib.pyplot as plt
# import subprocess

# Lang-segment用
!pip install -U git+https://github.com/luca-medeiros/lang-segment-anything.git
import warnings
import numpy as np
import matplotlib.pyplot as plt
import requests
from PIL import Image
from io import BytesIO
from lang_sam import LangSAM

  Cloning https://github.com/luca-medeiros/lang-segment-anything.git to /tmp/pip-req-build-pvfpe8xk
  Running command git clone --filter=blob:none --quiet https://github.com/luca-medeiros/lang-segment-anything.git /tmp/pip-req-build-pvfpe8xk
  Resolved https://github.com/luca-medeiros/lang-segment-anything.git to commit 134a48a81ebd691686187ecce2d016fb327a8852
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Cloning https://github.com/IDEA-Research/GroundingDINO.git to /tmp/pip-install-rwdogul_/groundingdino_33d65a20f7384619bd836753bf67e57f
  Running command git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO.git /tmp/pip-install-rwdogul_/groundingdino_33d65a20f7384619bd836753bf67e57f
  Resolved https://github.com/IDEA-Research/GroundingDINO.git to commit 60d796825e1266e56f7e4e9e00e88de662b67bd3
  Preparing metadata (setup.py) ... done
  Cloning https://github.com/fac

## lang_samで１番目のフレームでmaskを作る

In [ ]:
# # 第一フレームを取得
# def save_frame(video_path, frame_num, result_path):
#     cap = cv2.VideoCapture(video_path)

#     if not cap.isOpened():
#         return

#     os.makedirs(os.path.dirname(result_path), exist_ok=True)

#     cap.set(cv2.CAP_PROP_POS_FRAMES, frame_num)

#     ret, frame = cap.read()

#     if ret:
#         cv2.imwrite(result_path, frame)
# mv_2018_ls = [file_name for file_name in os.listdir("/content/drive/MyDrive/Colab Notebooks/2023年度スポコン/データ/2018WC") if file_name[-5] == "1"]
# vedio_path = "/content/drive/MyDrive/Colab Notebooks/2023年度スポコン/データ/2018WC/" + mv_2018_ls[0]
# result_path = "/content/drive/MyDrive/Colab Notebooks/2023年度スポコン/img/"+ mv_2018_ls[0][:-4] + ".png"
# save_frame(vedio_path, 1, result_path)

In [ ]:
# ## bboxの比較
# import math

# def calculate_distance(box1, box2):
#     center1 = (box1[0] + box1[2] / 2, box1[1] + box1[3] / 2)
#     center2 = (box2[0] + box2[2] / 2, box2[1] + box2[3] / 2)

#     distance = math.sqrt((center1[0] - center2[0])**2 + (center1[1] - center2[1])**2)
#     return distance

# def filter_farthest_box(bounding_boxes):
#     if len(bounding_boxes) < 2:
#         return bounding_boxes, None

#     farthest_box_index, farthest_box = max(enumerate(bounding_boxes), key=lambda box: max(calculate_distance(box[1], other) for idx, other in enumerate(bounding_boxes) if idx != box[0]))
#     filtered_boxes = [box for idx, box in enumerate(bounding_boxes) if idx != farthest_box_index]

#     return filtered_boxes, farthest_box_index

In [ ]:
import warnings
import numpy as np
import matplotlib.pyplot as plt
import requests
from PIL import Image
from io import BytesIO
from lang_sam import LangSAM
import os
import cv2
import torch
import gc

os.chdir("/content/drive/MyDrive/Colab Notebooks/2023年度スポコン/データ/2018WC_3seconds")
mv_2018_ls = [os.getcwd() + "/" + file_name for file_name in os.listdir(os.getcwd()) if file_name[-6:-4] == "_1"]

# text_prompt = "people in white and blue on the yellow floor"
# text_prompt = "only the person in white and the person in blue on the yellow floor and the yellow floor."
# text_prompt = "only two person in white and blue on the yellow floor and the yellow floor."
text_prompt = "one person in the black suit on the yellow floor"
# text_prompt = "three person in white and in blue and in black on the yellow floor, the yellow floor."

def download_image(url):
    response = requests.get(url)
    response.raise_for_status()
    return Image.open(BytesIO(response.content)).convert("RGB")

def save_mask(mask_np, filename):
    mask_image = Image.fromarray((mask_np * 255).astype(np.uint8))
    mask_image.save(filename)

def display_image_with_masks(image, masks):
    num_masks = len(masks)

    fig, axes = plt.subplots(1, num_masks + 1, figsize=(15, 5))
    axes[0].imshow(image)
    axes[0].set_title("Original Image")
    axes[0].axis('off')

    for i, mask_np in enumerate(masks):
        axes[i+1].imshow(mask_np, cmap='gray')
        axes[i+1].set_title(f"Mask {i+1}")
        axes[i+1].axis('off')

    plt.tight_layout()
    plt.show()

def display_image_with_boxes(image, boxes, logits):
    fig, ax = plt.subplots()
    ax.imshow(image)
    ax.set_title("Image with Bounding Boxes")
    ax.axis('off')

    for box, logit in zip(boxes, logits):
        x_min, y_min, x_max, y_max = box
        confidence_score = round(logit.item(), 2)  # Convert logit to a scalar before rounding
        box_width = x_max - x_min
        box_height = y_max - y_min

        # Draw bounding box
        rect = plt.Rectangle((x_min, y_min), box_width, box_height, fill=False, edgecolor='red', linewidth=2)
        ax.add_patch(rect)

        # Add confidence score as text
        ax.text(x_min, y_min, f"Confidence: {confidence_score}", fontsize=8, color='red', verticalalignment='top')

    plt.show()

def print_bounding_boxes(boxes):
    print("Bounding Boxes:")
    for i, box in enumerate(boxes):
        print(f"Box {i+1}: {box}")

def print_detected_phrases(phrases):
    print("\nDetected Phrases:")
    for i, phrase in enumerate(phrases):
        print(f"Phrase {i+1}: {phrase}")

def print_logits(logits):
    print("\nConfidence:")
    for i, logit in enumerate(logits):
        print(f"Logit {i+1}: {logit}")

def do_system(arg):
	print(f"==== running: {arg}")
	err = os.system(arg)
	if err:
		print("FATAL: command failed")
		sys.exit(err)

def main():
    # Suppress warning messages
    warnings.filterwarnings("ignore")

    try:
        # if image.startswith("http"):
        #     image_pil = download_image(image)
        # else:
        #     image_pil = Image.open(image).convert("RGB")

        model = LangSAM()

        start_frame = 0
        fps_ls = []
        img_path_ls = []
        for video_name, video_path in enumerate(mv_2018_ls):
          count = 0

          cap = cv2.VideoCapture(video_path)
          cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

          fps_ls.append(int(cap.get(cv2.CAP_PROP_FPS)))

          img_save_dir = "/content/drive/MyDrive/Colab Notebooks/2023年度スポコン/2018WC_3seconds"
          # 出力ディレクトリが存在しない場合、作成します。
          if not os.path.exists(img_save_dir):
              os.makedirs(img_save_dir)

          img_path = img_save_dir + "/video/" + [file_name for file_name in os.listdir(os.getcwd()) if file_name[-6:-4] == "_1"][video_name][:-6]
          print(img_path)
          img_path_ls.append(img_path)
          # 出力ディレクトリが存在しない場合、作成します。
          if not os.path.exists(img_path):
              os.makedirs(img_path)

          while cap.isOpened():
            torch.cuda.empty_cache()
            # del variables
            gc.collect()

            torch.cuda.memory_summary(device=None, abbreviated=False)

            ret, frame = cap.read()

            if not ret:
              # print("no image")
              break

            image_pil = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))

            masks, boxes, phrases, logits = model.predict(image_pil, text_prompt)

            if len(masks) == 0:
              print(f"No objects of the '{text_prompt}' prompt detected in the image.")
            else:

              ## Convert masks to numpy arrays
              masks_np = [mask.squeeze().cpu().numpy() for mask in masks]

              # Display the original image and masks side by side
              display_image_with_masks(image_pil, masks_np)

              # Display the image with bounding boxes and confidence scores
              display_image_with_boxes(image_pil, boxes, logits)

              # # Save the masks
              # for i, mask_np in enumerate(masks_np):
              #     mask_path = f"{os.getcwd()}/image_mask_{i+1}.png"
              #     save_mask(mask_np, mask_path)

              # Print the bounding boxes, phrases, and logits
              print_bounding_boxes(boxes)
              print_detected_phrases(phrases)
              print_logits(logits)


              ## 審判以外の予測を取り出す
              # print(phrases)
              player_label_idx = []
              for idx, phrase in enumerate(phrases):
                if not ('the yellow floor the yellow floor' in phrase):

                  player_label_idx.append(idx)

              # print(player_label_idx)
              masks_np = [masks_np[idx] for idx in player_label_idx]
              # display_image_with_masks(image_pil, masks_np)

              # ## bboxの座標が最も遠いマスクを除外する
              # boxes = [list(box.squeeze().cpu().numpy()) for box in boxes]
              # print(boxes)
              # _, farthest_box_index = filter_farthest_box(boxes)
              # masks_np = [masks_np[idx] for idx in range(len(boxes)) if idx != farthest_box_index]

              # display_image_with_masks(image_pil, masks_np)


              ## 全てのマスクを合わせる
              masks_np = sum(masks_np).astype(bool)

              masks_np = cv2.cvtColor(masks_np.astype(np.uint8) * 255, cv2.COLOR_GRAY2BGR)

              # masks_np = np.concatenate([masks_np, masks_np, masks_np])
              frame = cv2.cvtColor(np.array(image_pil), cv2.COLOR_RGB2BGR)

              result_img = cv2.bitwise_and(frame, masks_np)

              result_path = img_path + "/" + f"{str(count + 1).zfill(4)}.png"
              cv2.imwrite(result_path, result_img)
              count += 1
              break

    except (requests.exceptions.RequestException, IOError) as e:
      print(f"Error: {e}")
    return img_path_ls, fps_ls
if __name__ == "__main__":

    img_path_ls, fps_ls = main()
    for i, fps in zip(img_path_ls, fps_ls):
      video_name = i.split("/")[-1]
      do_system(f"yes | ffmpeg -framerate {str(fps)} -i '{i}/%04d.png' -pix_fmt yuv420p '{i}/{video_name}.mp4'")

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
import warnings
import numpy as np
import matplotlib.pyplot as plt
import requests
from PIL import Image
from io import BytesIO
from lang_sam import LangSAM
import os
import cv2
import torch
import gc

os.chdir("/content/drive/MyDrive/Colab Notebooks/2023年度スポコン/データ/2018WC_3seconds")
mv_2018_ls = [os.getcwd() + "/" + file_name for file_name in os.listdir(os.getcwd()) if file_name[-6:-4] == "_1"]

# text_prompt = "people in white and blue on the yellow floor"
# text_prompt = "only the person in white and the person in blue on the yellow floor and the yellow floor."
# text_prompt = "only two person in white and blue on the yellow floor and the yellow floor."
text_prompt = "two person in white and in blue on the yellow floor, the yellow floor."
# text_prompt = "three person in white and in blue and in black on the yellow floor, the yellow floor."

def download_image(url):
    response = requests.get(url)
    response.raise_for_status()
    return Image.open(BytesIO(response.content)).convert("RGB")

def save_mask(mask_np, filename):
    mask_image = Image.fromarray((mask_np * 255).astype(np.uint8))
    mask_image.save(filename)

def display_image_with_masks(image, masks):
    num_masks = len(masks)

    fig, axes = plt.subplots(1, num_masks + 1, figsize=(15, 5))
    axes[0].imshow(image)
    axes[0].set_title("Original Image")
    axes[0].axis('off')

    for i, mask_np in enumerate(masks):
        axes[i+1].imshow(mask_np, cmap='gray')
        axes[i+1].set_title(f"Mask {i+1}")
        axes[i+1].axis('off')

    plt.tight_layout()
    plt.show()

def display_image_with_boxes(image, boxes, logits):
    fig, ax = plt.subplots()
    ax.imshow(image)
    ax.set_title("Image with Bounding Boxes")
    ax.axis('off')

    for box, logit in zip(boxes, logits):
        x_min, y_min, x_max, y_max = box
        confidence_score = round(logit.item(), 2)  # Convert logit to a scalar before rounding
        box_width = x_max - x_min
        box_height = y_max - y_min

        # Draw bounding box
        rect = plt.Rectangle((x_min, y_min), box_width, box_height, fill=False, edgecolor='red', linewidth=2)
        ax.add_patch(rect)

        # Add confidence score as text
        ax.text(x_min, y_min, f"Confidence: {confidence_score}", fontsize=8, color='red', verticalalignment='top')

    plt.show()

def print_bounding_boxes(boxes):
    print("Bounding Boxes:")
    for i, box in enumerate(boxes):
        print(f"Box {i+1}: {box}")

def print_detected_phrases(phrases):
    print("\nDetected Phrases:")
    for i, phrase in enumerate(phrases):
        print(f"Phrase {i+1}: {phrase}")

def print_logits(logits):
    print("\nConfidence:")
    for i, logit in enumerate(logits):
        print(f"Logit {i+1}: {logit}")

def do_system(arg):
	print(f"==== running: {arg}")
	err = os.system(arg)
	if err:
		print("FATAL: command failed")
		sys.exit(err)

def main():
    # Suppress warning messages
    warnings.filterwarnings("ignore")

    try:
        # if image.startswith("http"):
        #     image_pil = download_image(image)
        # else:
        #     image_pil = Image.open(image).convert("RGB")

        model = LangSAM()

        start_frame = 0
        fps_ls = []
        img_path_ls = []
        for video_name, video_path in enumerate(mv_2018_ls[25:26]):
          count = 0

          cap = cv2.VideoCapture(video_path)
          cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

          fps_ls.append(int(cap.get(cv2.CAP_PROP_FPS)))

          img_save_dir = "/content/drive/MyDrive/Colab Notebooks/2023年度スポコン/2018WC_3seconds"
          # 出力ディレクトリが存在しない場合、作成します。
          if not os.path.exists(img_save_dir):
              os.makedirs(img_save_dir)

          img_path = img_save_dir + "/video/" + [file_name for file_name in os.listdir(os.getcwd()) if file_name[-6:-4] == "_1"][video_name][:-6]
          print(img_path)
          img_path_ls.append(img_path)
          # 出力ディレクトリが存在しない場合、作成します。
          if not os.path.exists(img_path):
              os.makedirs(img_path)

          while cap.isOpened():
            torch.cuda.empty_cache()
            # del variables
            gc.collect()

            torch.cuda.memory_summary(device=None, abbreviated=False)

            ret, frame = cap.read()

            if not ret:
              # print("no image")
              break

            image_pil = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))

            masks, boxes, phrases, logits = model.predict(image_pil, text_prompt)

            if len(masks) == 0:
              print(f"No objects of the '{text_prompt}' prompt detected in the image.")
            else:

              ## Convert masks to numpy arrays
              masks_np = [mask.squeeze().cpu().numpy() for mask in masks]

              # # Display the original image and masks side by side
              # display_image_with_masks(image_pil, masks_np)

              # # Display the image with bounding boxes and confidence scores
              # display_image_with_boxes(image_pil, boxes, logits)

              # # # Save the masks
              # # for i, mask_np in enumerate(masks_np):
              # #     mask_path = f"{os.getcwd()}/image_mask_{i+1}.png"
              # #     save_mask(mask_np, mask_path)

              # # Print the bounding boxes, phrases, and logits
              # print_bounding_boxes(boxes)
              # print_detected_phrases(phrases)
              # print_logits(logits)


              ## 審判以外の予測を取り出す
              # print(phrases)
              player_label_idx = []
              for idx, phrase in enumerate(phrases):
                if not ('the yellow floor the yellow floor' in phrase):

                  player_label_idx.append(idx)

              # print(player_label_idx)
              masks_np = [masks_np[idx] for idx in player_label_idx]
              # display_image_with_masks(image_pil, masks_np)

              # ## bboxの座標が最も遠いマスクを除外する
              # boxes = [list(box.squeeze().cpu().numpy()) for box in boxes]
              # print(boxes)
              # _, farthest_box_index = filter_farthest_box(boxes)
              # masks_np = [masks_np[idx] for idx in range(len(boxes)) if idx != farthest_box_index]

              # display_image_with_masks(image_pil, masks_np)


              ## 全てのマスクを合わせる
              masks_np = sum(masks_np).astype(bool)

              masks_np = cv2.cvtColor(masks_np.astype(np.uint8) * 255, cv2.COLOR_GRAY2BGR)

              # masks_np = np.concatenate([masks_np, masks_np, masks_np])
              frame = cv2.cvtColor(np.array(image_pil), cv2.COLOR_RGB2BGR)

              result_img = cv2.bitwise_and(frame, masks_np)

              result_path = img_path + "/" + f"{str(count + 1).zfill(4)}.png"
              cv2.imwrite(result_path, result_img)
              count += 1
              # break

    except (requests.exceptions.RequestException, IOError) as e:
      print(f"Error: {e}")
    return img_path_ls, fps_ls
if __name__ == "__main__":

    img_path_ls, fps_ls = main()
    for i, fps in zip(img_path_ls, fps_ls):
      video_name = i.split("/")[-1]
      do_system(f"yes | ffmpeg -framerate {str(fps)} -i '{i}/%04d.png' -pix_fmt yuv420p '{i}/{video_name}.mp4'")

In [ ]:
# #　指定の試合動画を見つけたい
# for i in range(len(mv_2018_ls)):
#   if mv_2018_ls[i].split("/")[-1][:-6] == "2018WCB_48_P1_KRASNIQI Distria_KOS_SOLIS Jacqueline_GUA":
#     print(i, " : ", mv_2018_ls[i])

25  :  /content/drive/.shortcut-targets-by-id/1wERFTJ3tk-moekRG-4KtAeT8uJewI1Y3/データ/2018WC_3seconds/2018WCB_48_P1_KRASNIQI Distria_KOS_SOLIS Jacqueline_GUA_1.mp4


In [ ]:
# # bbox_mask作成
# import warnings
# import numpy as np
# import matplotlib.pyplot as plt
# import requests
# from PIL import Image
# from io import BytesIO
# from lang_sam import LangSAM

# image = result_path
# # image = "./image.jpg"
# text_prompt = "People in blue." +  "People in white."

# def download_image(url):
#     response = requests.get(url)
#     response.raise_for_status()
#     return Image.open(BytesIO(response.content)).convert("RGB")

# def save_mask(mask_np, filename):
#     mask_image = Image.fromarray((mask_np * 255).astype(np.uint8))
#     mask_image.save(filename)

# def display_image_with_masks(image, masks):
#     num_masks = len(masks)

#     fig, axes = plt.subplots(1, num_masks + 1, figsize=(15, 5))
#     axes[0].imshow(image)
#     axes[0].set_title("Original Image")
#     axes[0].axis('off')

#     for i, mask_np in enumerate(masks):
#         axes[i+1].imshow(mask_np, cmap='gray')
#         axes[i+1].set_title(f"Mask {i+1}")
#         axes[i+1].axis('off')

#     plt.tight_layout()
#     plt.show()

# def make_mask(image, boxes, logits):
#     fig, ax = plt.subplots()
#     ax.imshow(image)
#     ax.set_title("Image with Bounding Boxes")
#     ax.axis('off')

#     for box, logit in zip(boxes, logits):
#         x_min, y_min, x_max, y_max = box
#         left_up = (x_min, y_max)  # 左上座標
#         right_up = (x_max, y_max)  # 右上座標
#         left_low = (x_min, y_min)  # 左下座標
#         right_low = (x_max, y_min)  # 右下座標

#         coor_list = [left_up,  # 左上座標
#                       right_up,  # 右上座標
#                       right_low,  # 右下座標
#                       left_low  # 左下座標
#                       ]

#         # coor_list = [(x,y) for x, y in zip(coor_x, coor_y)]
#         pts = np.array(coor_list)
#         img_mask = img_mask*0
#         img_mask = cv2.fillPoly(img_mask, [pts], 255)

#         return img_mask

# def print_bounding_boxes(boxes):
#     print("Bounding Boxes:")
#     for i, box in enumerate(boxes):
#         print(f"Box {i+1}: {box}")

# def print_detected_phrases(phrases):
#     print("\nDetected Phrases:")
#     for i, phrase in enumerate(phrases):
#         print(f"Phrase {i+1}: {phrase}")

# def print_logits(logits):
#     print("\nConfidence:")
#     for i, logit in enumerate(logits):
#         print(f"Logit {i+1}: {logit}")

# def main():
#     # Suppress warning messages
#     warnings.filterwarnings("ignore")

#     try:
#         if image.startswith("http"):
#             image_pil = download_image(image)
#         else:
#             image_pil = Image.open(image).convert("RGB")

#         model = LangSAM()
#         masks, boxes, phrases, logits = model.predict(image_pil, text_prompt)

#         if len(masks) == 0:
#             print(f"No objects of the '{text_prompt}' prompt detected in the image.")
#         else:
#             # Convert masks to numpy arrays
#             masks_np = [mask.squeeze().cpu().numpy() for mask in masks]

#             # Display the original image and masks side by side
#             display_image_with_masks(image_pil, masks_np)

#             # Display the image with bounding boxes and confidence scores
#             img_mask = make_mask(image_pil, boxes, logits)
#             print(img_mask)
#             print(type(img_mask))

#             # # Save the masks
#             # for i, mask_np in enumerate(masks_np):
#             #     mask_path = f"image_mask_{i+1}.png"
#             #     save_mask(mask_np, mask_path)

#             # # Print the bounding boxes, phrases, and logits
#             # print_bounding_boxes(boxes)
#             # print_detected_phrases(phrases)
#             # print_logits(logits)

#     except (requests.exceptions.RequestException, IOError) as e:
#         print(f"Error: {e}")

# if __name__ == "__main__":
#     main()

# XMem　ダウンロード

In [ ]:
import locale
locale.getpreferredencoding = lambda: "UTF-8"

In [ ]:
!nvidia-smi

import torch

if torch.cuda.is_available():
  print('Using GPU')
  device = 'cuda'
else:
  print('CUDA not available. Please connect to a GPU instance if possible.')
  device = 'cpu'

Wed Nov  1 11:11:09 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P0    39W / 300W |   9256MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
!git clone https://github.com/hkchengrex/XMem.git
%cd XMem
!pip install opencv-python
!pip install -U numpy
!pip install -r requirements.txt

Cloning into 'XMem'...
remote: Enumerating objects: 596, done.
remote: Counting objects: 100% (324/324), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 596 (delta 233), reused 210 (delta 195), pack-reused 272
Receiving objects: 100% (596/596), 265.06 KiB | 3.19 MiB/s, done.
Resolving deltas: 100% (345/345), done.
/content/drive/MyDrive/Colab Notebooks/sports/sports_competition/XMemで両選手フォーカス/サンプル/XMem
  Cloning https://github.com/cheind/py-thin-plate-spline to /tmp/pip-req-build-vrd5a_fj
  Running command git clone --filter=blob:none --quiet https://github.com/cheind/py-thin-plate-spline /tmp/pip-req-build-vrd5a_fj
  Resolved https://github.com/cheind/py-thin-plate-spline to commit f6995795397118b7d0ac01aecd3f39ffbfad9dee
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.6/190.6 kB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.9/107.9 kB 10.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [ ]:
# Download the pretrained model
!wget -P ./saves/ https://github.com/hkchengrex/XMem/releases/download/v1.0/XMem.pth

--2023-11-01 11:09:29--  https://github.com/hkchengrex/XMem/releases/download/v1.0/XMem.pth
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/511262077/ea2968ee-04ab-4dee-8596-03319e8c7e9f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231101%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231101T110929Z&X-Amz-Expires=300&X-Amz-Signature=0b97a9bafffb36c93ecbbc8fa9348ec0a7c2eea455651597bbaac3fa929fd1d0&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=511262077&response-content-disposition=attachment%3B%20filename%3DXMem.pth&response-content-type=application%2Foctet-stream [following]
--2023-11-01 11:09:29--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/511262077/ea2968ee-04ab-4dee-8596-03319e8c7e9f?X-Amz-Algorithm=AWS4-HMAC

In [ ]:
# Basic setup
import os
from os import path
from argparse import ArgumentParser
import shutil

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader
import numpy as np
from PIL import Image

from inference.data.test_datasets import LongTestDataset, DAVISTestDataset, YouTubeVOSTestDataset
from inference.data.mask_mapper import MaskMapper
from model.network import XMem
from inference.inference_core import InferenceCore

from progressbar import progressbar

torch.set_grad_enabled(False)

# default configuration
config = {
    'top_k': 30,
    'mem_every': 5,
    'deep_update_every': -1,
    'enable_long_term': True,
    'enable_long_term_count_usage': True,
    'num_prototypes': 128,
    'min_mid_term_frames': 5,
    'max_mid_term_frames': 10,
    'max_long_term_elements': 10000,
}

network = XMem(config, './saves/XMem.pth').eval().to(device)

Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False


# XMemを使って白選手をフォーカス

## 白選手のmaskを作る

In [ ]:
video_name = vedio_path
mask_name = "/content/drive/MyDrive/Colab Notebooks/sports/sports_competition/XMemで両選手フォーカス/サンプル/image_mask_1.png"

In [ ]:
# Convert the mask to a numpy array
mask = np.array(Image.open(mask_name))
mask1 = mask / 255
print(mask)
print(np.unique(mask1))
num_objects = len(np.unique(mask1)) - 1
print(num_objects)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0. 1.]
1


In [ ]:
mask1.shape

(360, 640)

In [ ]:
print(np.unique(mask_name))
num_objects = len(np.unique(mask_name)) - 1

[  0 255]


In [ ]:
mask = np.array(mask_name)
print(type(mask))

<class 'numpy.ndarray'>


In [ ]:
mask = np.array(Image.open(mask_name))
print(np.unique(mask))
num_objects = len(np.unique(mask)) - 1

AttributeError: ignored

In [ ]:
# Propagte frame-by-frame
import cv2
from inference.interact.interactive_utils import image_to_torch, index_numpy_to_one_hot_torch, torch_prob_to_numpy_mask, overlay_davis

torch.cuda.empty_cache()

processor = InferenceCore(network, config=config)
processor.set_all_labels(range(1, num_objects+1)) # consecutive labels
cap = cv2.VideoCapture(video_name)

# You can change these two numbers
frames_to_propagate = 200
visualize_every = 20

current_frame_index = 0

with torch.cuda.amp.autocast(enabled=True):
  while (cap.isOpened()):
    # load frame-by-frame
    _, frame = cap.read()
    if frame is None or current_frame_index > frames_to_propagate:
      break

    # convert numpy array to pytorch tensor format
    frame_torch, _ = image_to_torch(frame, device=device)
    if current_frame_index == 0:
      # initialize with the mask
      mask_torch = index_numpy_to_one_hot_torch(mask, num_objects+1).to(device)
      # the background mask is not fed into the model
      prediction = processor.step(frame_torch, mask_torch[1:])
    else:
      # propagate only
      prediction = processor.step(frame_torch)

    # argmax, convert to numpy
    prediction = torch_prob_to_numpy_mask(prediction)

    if current_frame_index % visualize_every == 0:
      visualization = overlay_davis(frame, prediction)
      display(Image.fromarray(visualization))

    current_frame_index += 1

RuntimeError: ignored

In [ ]:
from numpy.ma.core import count
import cv2
from inference.interact.interactive_utils import image_to_torch, index_numpy_to_one_hot_torch, torch_prob_to_numpy_mask, overlay_davis

torch.cuda.empty_cache()

processor = InferenceCore(network, config=config)
processor.set_all_labels(range(1, num_objects+1)) # consecutive labels
cap = cv2.VideoCapture(video_name)
# フレームの総数
totalframecount = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) - first_frame
print(totalframecount)
#指定したフレームをセットする
cap.set(cv2.CAP_PROP_POS_FRAMES, first_frame)

# You can change these two numbers
frames_to_propagate = totalframecount
visualize_every = 200

current_frame_index = 0
count_value = 0
with torch.cuda.amp.autocast(enabled=True):
  while (cap.isOpened()):
    # load frame-by-frame
    _, frame = cap.read()
    if frame is None or current_frame_index > frames_to_propagate:
      break

    # convert numpy array to pytorch tensor format
    frame_torch, _ = image_to_torch(frame, device=device)
    if current_frame_index == 0:
      # initialize with the mask
      mask_torch = index_numpy_to_one_hot_torch(mask, num_objects+1).to(device)
      # the background mask is not fed into the model
      prediction = processor.step(frame_torch, mask_torch[1:])
    else:
      # propagate only
      prediction = processor.step(frame_torch)

    # argmax, convert to numpy
    prediction = torch_prob_to_numpy_mask(prediction)

    if current_frame_index % visualize_every == 1:
      visualization = overlay_davis(frame, prediction)
      # display(Image.fromarray(visualization))
      #cv2_imshow(visualization)
    #動画にフレーム数を表示する
    frame = cv2.putText(frame, f'{count_value}', org = (50, 50), fontFace = cv2.FONT_HERSHEY_PLAIN, fontScale = 1, color = (255, 255, 255), thickness = 1, lineType = cv2.LINE_AA)
    writer.write(frame)
    count_value += 1
    current_frame_index += 1
  cap.release()
  writer.release()

NameError: ignored

# XMemを使って青選手をフォーカス

## 青選手のmaskを作る

# XMemを使って両選手をフォーカス

## 二つのmaskを結合する

# make_bboxclipping_img

In [ ]:
# -*- coding: utf-8 -*-
import csv
import cv2
import os
import pandas as pd
import numpy as np

# original_cap = cv2.VideoCapture("/content/drive/MyDrive/2018WCB_60_P2_SELLO_Edwin_BOT_NAZIR_BIN_Abdou_MAD.mp4") #オリジナル動画
original_cap = cv2.VideoCapture(
    "/content/drive/MyDrive/Colab Notebooks/sports/sports_competition/XMemで両選手フォーカス/サンプル/2018WCB_P78_P3_SLUTSKAYA Maryna_BLR_ADLINGTON Sarah_GBR_1.mp4")
ret_ori, img_ori = original_cap.read()


# ret_mask, img_mask = cap_mask.read()

csv_make_list = ["Videoframe", "X_min",
                 "Y_min", "X_max", "Y_max"]  # csvファイルの形式決定
csv_df1 = pd.DataFrame([csv_make_list])  # 形式決定したものをデータフレームに変換
csv_df2 = pd.DataFrame([csv_make_list])  # 形式決定したものをデータフレームに変換

csv_save_path = "/content/drive/MyDrive/Colab Notebooks/sports/sports_competition/XMemで両選手フォーカス"  # csv保存先のディレクトリのpath
csv_make_path1 = os.path.join(
    csv_save_path, 'mask_bbox_coordinate_player1.csv')  # csv保存先のpath
csv_df1.to_csv(csv_make_path1, index=False)  # データフレームをCSVに変換

csv_make_path2 = os.path.join(
    csv_save_path, 'mask_bbox_coordinate_player2.csv')  # csv保存先のpath
csv_df2.to_csv(csv_make_path2, index=False)  # データフレームをCSVに変換


def bbox_for_mask1(img_mask, now_frame, plus=0):
    im = cv2.cvtColor(img_mask, cv2.COLOR_BGR2GRAY)  # グレースケール化 二次元配列にしないとダメ
    im = img_mask*255
    im = np.where(im == 255, True, False)  # 0,255をFalse,Trueに変換

    now_frame += 1  # 現在のフレーム

    ######## bbox座標の計算##################
    rows = np.any(im, axis=1)
    cols = np.any(im, axis=0)

    y_min, y_max = np.where(rows)[0][[0, -1]]
    x_min, x_max = np.where(cols)[0][[0, -1]]

    # print(im.shape)
    # print(y_min, y_max, x_min, x_max)

    left_up = (x_min - plus, y_max + plus)  # 左上座標
    right_up = (x_max + plus, y_max + plus)  # 右上座標
    left_low = (x_min, y_min)  # 左下座標
    right_low = (x_max, y_min)  # 右下座標

    coor_list = [left_up,  # 左上座標
                 right_up,  # 右上座標
                 right_low,  # 右下座標
                 left_low  # 左下座標
                 ]

    # coor_list = [(x,y) for x, y in zip(coor_x, coor_y)]
    pts = np.array(coor_list)
    img_mask = img_mask*0
    img_mask = cv2.fillPoly(img_mask, [pts], 255)

    #####################################

    ##### CSVの書き込み############
    with open(csv_make_path1, 'a') as f:
        writer = csv.writer(f)
        writer.writerow([now_frame, x_min, y_min, x_max, y_max])

    return img_mask


def bbox_for_mask2(img_mask, now_frame, plus=0):
    # im = cv2.cvtColor(img_mask, cv2.COLOR_BGR2GRAY) #グレースケール化 二次元配列にしないとダメ
    im = img_mask*255
    im = np.where(im == 255, True, False)  # 0,255をFalse,Trueに変換

    now_frame += 1  # 現在のフレーム

    ######## bbox座標の計算##################
    rows = np.any(im, axis=1)
    cols = np.any(im, axis=0)

    y_min, y_max = np.where(rows)[0][[0, -1]]
    x_min, x_max = np.where(cols)[0][[0, -1]]

    # print(im.shape)
    # print(y_min, y_max, x_min, x_max)

    left_up = (x_min - plus, y_max + plus)  # 左上座標
    right_up = (x_max + plus, y_max + plus)  # 右上座標
    left_low = (x_min, y_min)  # 左下座標
    right_low = (x_max, y_min)  # 右下座標

    coor_list = [left_up,  # 左上座標
                 right_up,  # 右上座標
                 right_low,  # 右下座標
                 left_low  # 左下座標
                 ]

    # coor_list = [(x,y) for x, y in zip(coor_x, coor_y)]
    pts = np.array(coor_list)
    img_mask = img_mask*0
    cv2.fillPoly(img_mask, [pts], 255)

    #####################################

    ##### CSVの書き込み############
    with open(csv_make_path2, 'a') as f:
        writer = csv.writer(f)
        writer.writerow([now_frame, x_min, y_min, x_max, y_max])

    return img_mask
