# 2.5 手順２ colmap　MVSで高密度点群作成

In [ ]:
import os

img_directory = os.path.join(os.getcwd(), "images")
dense_directory = os.path.join(os.getcwd(), "dense")
sparse_directory = os.path.join(os.getcwd(), "colmap_text")

# 出力ディレクトリが存在しない場合
if not os.path.exists(dense_directory):
    os.makedirs(dense_directory)

os.system(f'yes | colmap image_undistorter --image_path {img_directory} --input_path {sparse_directory} --output_path {dense_directory} --output_type COLMAP --max_image_size 2000')
os.system(f'yes | colmap patch_match_stereo --workspace_path {dense_directory} --workspace_format COLMAP --PatchMatchStereo.geom_consistency true')
os.system(f'yes | colmap stereo_fusion --workspace_path {dense_directory} --workspace_format COLMAP --input_type geometric --output_path {dense_directory}/fused.ply')
os.system(f'yes | colmap poisson_mesher --input_path {dense_directory}/fused.ply --output_path {dense_directory}/meshed-poisson.ply')
os.system(f'yes | colmap delaunay_mesher --input_path {dense_directory} --output_path {dense_directory}/meshed-delaunay.ply')


Reading reconstruction

 => Reconstruction with 1050 images and 53272 points

Image undistortion

Undistorting image [1/1050]
Undistorting image [2/1050]
Undistorting image [3/1050]
Undistorting image [4/1050]
Undistorting image [5/1050]
Undistorting image [6/1050]
Undistorting image [7/1050]
Undistorting image [8/1050]
Undistorting image [9/1050]
Undistorting image [10/1050]
Undistorting image [11/1050]
Undistorting image [12/1050]
Undistorting image [13/1050]
Undistorting image [14/1050]
Undistorting image [15/1050]
Undistorting image [16/1050]
Undistorting image [17/1050]
Undistorting image [18/1050]
Undistorting image [19/1050]
Undistorting image [20/1050]
Undistorting image [21/1050]
Undistorting image [22/1050]
Undistorting image [23/1050]
Undistorting image [24/1050]
Undistorting image [25/1050]
Undistorting image [26/1050]
Undistorting image [27/1050]
Undistorting image [28/1050]
Undistorting image [29/1050]
Undistorting image [30/1050]
Undistorting image [31/1050]
Undistortin

yes: 標準出力: Broken pipe


Reading configuration...
Configuration has 1050 problems...

Processing view 1 / 1050 for 0541.png

Reading inputs...

PatchMatch::Problem
-------------------
ref_image_idx: 681
src_image_idxs: 691 689 684 690 688 687 685 686 692 669 672 670 671 673 683 682 674 676 675 677

PatchMatchOptions
-----------------
max_image_size: -1
gpu_index: 0
depth_min: 11600.2
depth_max: 47188.1
window_radius: 5
window_step: 1
sigma_spatial: 5
sigma_color: 0.2
num_samples: 15
ncc_sigma: 0.6
min_triangulation_angle: 1
incident_angle_sigma: 0.9
num_iterations: 5
geom_consistency: 0
geom_consistency_regularizer: 0.3
geom_consistency_max_cost: 3
filter: 0
filter_min_ncc: 0.1
filter_min_triangulation_angle: 3
filter_min_num_consistent: 2
filter_geom_consistency_max_cost: 1
write_consistency_graph: 0
allow_missing_files: 0

PatchMatch::Run
---------------
Initialization: 0.0910s
 Sweep 1: 0.4805s
 Sweep 2: 0.8146s
 Sweep 3: 0.4553s
 Sweep 4: 0.8066s
Iteration 1: 2.5570s
 Sweep 1: 0.4513s
 Sweep 2: 0.7948s
 Sw

yes: 標準出力: Broken pipe



StereoFusion::Options
---------------------
mask_path: 
max_image_size: -1
min_num_pixels: 5
max_num_pixels: 10000
max_traversal_depth: 100
max_reproj_error: 2
max_depth_error: 0.01
max_normal_error: 10
check_num_images: 50
use_cache: 0
cache_size: 32
bbox_min: -3.40282e+38 -3.40282e+38 -3.40282e+38
bbox_max: 3.40282e+38 3.40282e+38 3.40282e+38

Reading workspace...
Loading workspace data with 4 threads...
Elapsed time: 0.924 [minutes]
Reading configuration...
Starting fusion with 4 threads
Fusing image [1/1050] with index 0 in 6.340s (246708 points)
Fusing image [2/1050] with index 681 in 3.667s (400184 points)
Fusing image [3/1050] with index 679 in 2.994s (529692 points)
Fusing image [4/1050] with index 677 in 3.018s (670475 points)
Fusing image [5/1050] with index 690 in 4.013s (854069 points)
Fusing image [6/1050] with index 691 in 2.517s (980875 points)
Fusing image [7/1050] with index 692 in 2.092s (1083583 points)
Fusing image [8/1050] with index 693 in 1.731s (1168961 points)

yes: 標準出力: Broken pipe


Value Range: [2.003541,16.020803]


yes: 標準出力: Broken pipe


Triangulating points...
Triangulation has 890422 using 29107004 points.
Initializing ray tracer...
Initializing graph optimization...
Integrating image [1/1050] in 5.193s
Integrating image [2/1050] in 3.061s
Integrating image [3/1050] in 0.909s
Integrating image [4/1050] in 1.904s
Integrating image [5/1050] in 1.779s
Integrating image [6/1050] in 1.674s
Integrating image [7/1050] in 3.012s
Integrating image [8/1050] in 2.065s
Integrating image [9/1050] in 3.990s
Integrating image [10/1050] in 2.793s
Integrating image [11/1050] in 2.174s
Integrating image [12/1050] in 2.840s
Integrating image [13/1050] in 3.773s
Integrating image [14/1050] in 3.452s
Integrating image [15/1050] in 1.858s
Integrating image [16/1050] in 3.777s
Integrating image [17/1050] in 2.991s
Integrating image [18/1050] in 3.871s
Integrating image [19/1050] in 1.267s
Integrating image [20/1050] in 4.091s
Integrating image [21/1050] in 2.541s
Integrating image [22/1050] in 0.522s
Integrating image [23/1050] in 2.060s
I

yes: 標準出力: Broken pipe


0

#  add camera coordinate

In [ ]:
import os
base_cam_path = os.path.join(os.getcwd(), "base_cam.json")
# NeRF_mesh_camera_points_path = os.path.join(os.getcwd(), "nerf_mesh_camera_points.ply")
NeRF_mesh_camera_points_path = os.path.join(os.getcwd(), "mesh_camera_points.ply")

In [ ]:
import json
import numpy as np

# base_cam.jsonから回転行列と平行移動ベクトルを取得
with open(base_cam_path, 'r') as f:
    base_cam_data = json.load(f)

# 2.5の手順１の(3)式に対応
# カメラの中心座標を適切な座標系に変換して追加
with open(NeRF_mesh_camera_points_path, 'w') as ply_file:
    ply_file.write("ply\nformat ascii 1.0\n")
    ply_file.write("comment Added camera center coordinates\n")
    ply_file.write(f"element vertex {len(base_cam_data['path'])}\n")
    ply_file.write("property float x\nproperty float y\nproperty float z\n")
    ply_file.write("property uchar red\nproperty uchar green\nproperty uchar blue\n")
    ply_file.write("end_header\n")
    for i in range(len(base_cam_data['path'])):
        cx = (base_cam_data['path'][i]['T'][0] - 0.025 - 0.5)/0.33
        cy = (base_cam_data['path'][i]['T'][1] - 0.025 - 0.5)/0.33
        cz = (base_cam_data['path'][i]['T'][2] - 0.025 - 0.5)/0.33
        R = np.array([[0,1,0],[1,0,0],[0,0,-1]])
        x,y,z = np.dot(R,np.array([cx,cy,cz]))
        # plyファイルにカメラの中心座標を追加
        ply_file.write(f"{cx:.5f} {cy:.5f} {cz:.5f} 255 0 0\n")


# 2.5の手順2 colmapカメラ座標点群生成

In [ ]:
import numpy as np

import json

def parse_images_txt(file_path, output_file_path):
    # ファイルを読み込んで行ごとに処理
    with open(file_path, "r") as images_text:
        lines = images_text.readlines()

    # 画像情報を格納するリスト
    image_data = []

    for i in range(len(lines)):
        line = lines[i].strip()
        if line.startswith("#"):
            continue

        if i % 2 == 0:
            # 画像情報の行
            image_info = line.split(" ")
            image_id = int(image_info[0])
            qw, qx, qy, qz = map(float, image_info[1:5])
            tx, ty, tz = map(float, image_info[5:8])
            camera_id = int(image_info[8])
            name = image_info[9]

            current_image = {
                'IMAGE_ID': image_id,
                'QW': qw,
                'QX': qx,
                'QY': qy,
                'QZ': qz,
                'TX': tx,
                'TY': ty,
                'TZ': tz,
                'CAMERA_ID': camera_id,
                'NAME': name,
                'POINTS2D': []
            }
        else:
            # 画像の座標と特徴量情報
            feature_ls = line.split(" ")
            for j in range(2, len(feature_ls), 3):
                if feature_ls[j] != '-1':
                    x, y, point3d_id = map(float, feature_ls[j - 2:j + 1])
                    current_image['POINTS2D'].append((x, y, str(int(point3d_id))))

            # -1以外の画像情報をリストに追加
            if current_image['IMAGE_ID'] != -1:
                image_data.append(current_image)

    os.makedirs(os.path.join(os.getcwd(), 'json'), exist_ok=True)
    with open(os.path.join(os.getcwd(), 'json', output_file_path), 'w') as json_file:
        json.dump(image_data, json_file, indent=4)

    print(f"画像情報を {output_file_path} に保存しました。")

    return image_data

image_data = parse_images_txt(file_path=os.path.join(os.getcwd(), "colmap_text", "images.txt"), output_file_path="image_data.json")

# カメラの中心座標を適切な座標系に変換して追加
with open(os.path.join(os.getcwd(), "colmap_camera_points.ply"), 'w') as ply_file:
    ply_file.write("ply\nformat ascii 1.0\n")
    ply_file.write("comment Added camera center coordinates\n")
    ply_file.write(f"element vertex {len(base_cam_data['path'])}\n")
    ply_file.write("property float x\nproperty float y\nproperty float z\n")
    ply_file.write("property uchar red\nproperty uchar green\nproperty uchar blue\n")
    ply_file.write("end_header\n")

    for i in range(len(image_data)):
        # 画像毎の四元数と並進ベクトルを取り出す
        qw, qx, qy, qz, tx, ty, tz = image_data[i]['QW'], image_data[i]['QX'], image_data[i]['QY'], image_data[i]['QZ'], image_data[i]['TX'], image_data[i]['TY'], image_data[i]['TZ']

        # 四元数を正規化
        quaternion = np.array([qw, qx, qy, qz])
        quaternion /= np.linalg.norm(quaternion)

        # 四元数から回転行列を計算
        R = np.array([
            [1 - 2*qy*qy - 2*qz*qz, 2*qx*qy - 2*qz*qw, 2*qx*qz + 2*qy*qw],
            [2*qx*qy + 2*qz*qw, 1 - 2*qx*qx - 2*qz*qz, 2*qy*qz - 2*qx*qw],
            [2*qx*qz - 2*qy*qw, 2*qy*qz + 2*qx*qw, 1 - 2*qx*qx - 2*qy*qy]
        ])

        # カメラ座標から世界座標に変換する
        translation = np.array([tx, ty, tz])
        camera_center = -np.dot(np.transpose(R), translation)
        cx, cy, cz = camera_center
        ply_file.write(f"{cx:.5f} {cy:.5f} {cz:.5f} 255 0 0\n")
        # print(i+1, cx, cy, cz)

画像情報を image_data.json に保存しました。


# NeRF Mesh

In [ ]:
import open3d as o3d

## nerfのMeshを読み込む
nerf_mesh_name = 'nerf.ply'
nerf_mesh_path = os.path.join(os.getcwd(), nerf_mesh_name)

# PLYファイルを読み込む
nerf_mesh = o3d.io.read_triangle_mesh(nerf_mesh_path)

##
print(nerf_mesh)
#　頂点
print('Vertices:')
print(np.asarray(nerf_mesh.vertices))
#　三角形
print('Triangles:')
print(np.asarray(nerf_mesh.triangles))
##
# メッシュのカメラの中心座標を取得
nerf_mesh.compute_vertex_normals()  # 頂点法線を計算
nerf_mesh_center = nerf_mesh.get_center()

# 結果を表示
print("NeRF Meshの中心座標:", nerf_mesh_center)


In [ ]:
import open3d as o3d

# NeRf Meshのカメラ座標を読み込む
mesh_camera_points = o3d.io.read_triangle_mesh(NeRF_mesh_camera_points_path)

# メッシュのカメラの中心座標を取得
mesh_camera_points.compute_vertex_normals()  # 頂点法線を計算
mesh_camera_points_center = mesh_camera_points.get_center()

# 結果を表示
print("NeRF Meshのカメラ座標の中心座標:", mesh_camera_points_center)


[Open3D WARNING] geometry::TriangleMesh appears to be a geometry::PointCloud (only contains vertices, but no triangles).
NeRF Meshのカメラ座標の中心座標: [-0.82436153  1.81742287  0.99458361]


# NeRF Mesh Denoising

In [ ]:
## ノイズが多い場合
# # Taubin filter : Meshを縮小せずにノイズ除去できる
# print('filter with Taubin with 10 iterations')
# nerf_mesh = nerf_mesh.filter_smooth_taubin(number_of_iterations=10)
# nerf_mesh.compute_vertex_normals()

# # 保存する
# nerf_mesh_path = f"{os.getcwd()}/{nerf_mesh_name[:-4] + '_denoising.ply'}"
# o3d.io.write_triangle_mesh(nerf_mesh_path, nerf_mesh)

filter with Taubin with 10 iterations
[Open3D WARNING] Write Ply clamped color value to valid range


True

# 点群の結合

In [ ]:
# 点群の再サンプリング
import open3d as o3d

# NeRF点群の読み込み
point_cloud = o3d.io.read_point_cloud(nerf_mesh_path)
# 重複する点を削除して再サンプリング
downsampled_point_cloud = point_cloud.voxel_down_sample(voxel_size=0.01)

print(point_cloud.points)
print(downsampled_point_cloud)

output_path = os.path.join(getcwd(), "sampling_mesh.ply")
o3d.io.write_point_cloud(output_path, downsampled_point_cloud)

std::vector<Eigen::Vector3d> with 34631680 elements.
Use numpy.asarray() to access data.
PointCloud with 24551763 points.


True

In [ ]:
# nerf

import numpy as np
import open3d as o3d

mesh1_path = output_path
camera1_path = mesh_camera_points_path

mesh1 = o3d.io.read_point_cloud(mesh1_path)
camera1 = o3d.io.read_point_cloud(camera1_path)

combined_nerf = mesh1 + camera1

output_path = os.path.join(os.getcwd(), "combined_nerf.ply")
o3d.io.write_point_cloud(output_path, combined_nerf)


# colmap
mesh2_path = os.path.join(os.getcwd(), "dense", "meshed-poisson.ply")
camera2_path = os.path.join(os.getcwd(), "colmap_camera_points.ply")

mesh2 = o3d.io.read_point_cloud(mesh2_path)
camera2 = o3d.io.read_point_cloud(camera2_path)

combined_colmap = mesh2 + camera2

output_path = os.path.join(os.getcwd(), "combined_colmap.ply")
o3d.io.write_point_cloud(output_path, combined_colmap)

True

In [ ]:
import open3d as o3d
import numpy as np

# MVS点群とInstantNGP点群のパス
colmap_path = os.path.join(os.getcwd(), "combined_colmap.ply")
nerf_path = os.path.join(os.getcwd(), "combined_nerf.ply")

# MVS点群とInstantNGP点群を読み込む
colmap_mesh = o3d.io.read_triangle_mesh(colmap_path)
nerf_mesh = o3d.io.read_triangle_mesh(nerf_path)

# InstantNGP点群をMVS点群の座標系に移動
nerf_mesh_center = nerf_mesh.get_center()
colmap_mesh_center = colmap_mesh.get_center()
translation_vector = colmap_mesh_center - nerf_mesh_center
print(translation_vector)
nerf_mesh.translate(translation_vector)

# MVS点群のスケールを取得
colmap_mesh_size = np.linalg.norm(colmap_mesh.get_max_bound() - colmap_mesh.get_min_bound())
print(colmap_mesh.get_max_bound() - colmap_mesh.get_min_bound(), colmap_mesh_size)
# InstantNGP点群のサイズを取得
nerf_mesh_size = np.linalg.norm(nerf_mesh.get_max_bound() - nerf_mesh.get_min_bound())
print(nerf_mesh.get_max_bound() - nerf_mesh.get_min_bound(), nerf_mesh_size)
print((colmap_mesh.get_max_bound() - colmap_mesh.get_min_bound())/(nerf_mesh.get_max_bound() - nerf_mesh.get_min_bound()))
# InstantNGP点群をMVS点群と同じ大きさにスケール変換
scale_factor = colmap_mesh_size / nerf_mesh_size
nerf_mesh.scale(scale_factor, center=nerf_mesh.get_center())

# 結合されたメッシュを作成
mesh_combined = nerf_mesh

# 結合されたメッシュを保存
output_mesh_path = os.path.join(os.getcwd(), "scaled_combined_nerf.ply")
o3d.io.write_triangle_mesh(output_mesh_path, mesh_combined)


[Open3D WARNING] geometry::TriangleMesh appears to be a geometry::PointCloud (only contains vertices, but no triangles).
[Open3D WARNING] geometry::TriangleMesh appears to be a geometry::PointCloud (only contains vertices, but no triangles).
[30284.12663 32075.77144 25236.65876] 50821.96753945765
[6.94056 0.95878 8.01714] 10.647307921798825


True

In [ ]:
# カメラ座標を表示する
nerf = np.array(o3d.io.read_point_cloud(os.path.join(os.getcwd(), "scaled_combined_nerf.ply").points))
print(len(nerf[-1050:]))
print(nerf[-1050:])
colmap = np.array(o3d.io.read_point_cloud(os.path.join(os.getcwd(), "combined_colmap.ply").points))
print(len(colmap[-1050:]))
print(colmap[-1050:])

1050
[[-4138118.20363162  4125316.84192538  2621539.16036778]
 [-4138199.77799941  4125325.52918942  2621507.03658164]
 [-4138278.87029271  4125323.61990152  2621470.90328936]
 ...
 [-4158959.04681029  4126135.59274509  2612442.49651692]
 [-4159060.47778287  4126135.8314058   2612398.48740789]
 [-4159164.05670629  4126140.74782441  2612352.33034804]]
1050
[[-4162455.15836  4093068.85082  2596073.77679]
 [-4162547.28689  4093120.22368  2595857.42365]
 [-4162593.31724  4093142.48111  2595746.8981 ]
 ...
 [-4143835.14129  4106297.987    2604881.54437]
 [-4151697.48838  4113105.40368  2583434.85301]
 [-4143926.24151  4106155.49118  2604961.65523]]
